# Generated by Django 4.0.4 on 2022-05-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_brand_buyer_category_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('basePrice', models.IntegerField()),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('finalPrice', models.IntegerField(blank=True, default=0, null=True)),
                ('img1', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('img2', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('img3', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('img4', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.seller')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.subcategory')),
            ],
        ),
    ]
