# Generated by Django 4.0.4 on 2022-05-10 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_cart_contact_wishlist_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
