# Generated by Django 4.0.4 on 2022-05-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='address1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
