# Generated by Django 4.0.4 on 2022-05-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_product_size1_product_size2_product_size3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
