# Generated by Django 4.0.4 on 2022-05-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_alter_checkout_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='cart',
        ),
        migrations.AddField(
            model_name='checkout',
            name='buyer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.buyer'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.product'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='quantity',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='checkout',
            name='size',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total',
            field=models.IntegerField(default=None),
        ),
    ]
